const userConstant = {
  SIGN_USER_REQUEST: 'SIGN_USER_REQUEST',
  SIGN_USER_SUCCESS: 'SIGN_USER_SUCCESS',
  SIGN_USER_FAIL: 'SIGN_USER_FAIL',

  LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAIL: 'LOAD_USER_FAIL',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

  CLEAR_ERRORS: 'CLEAR_ERRORS',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES'
};

export const {
  SIGN_USER_REQUEST,
  SIGN_USER_SUCCESS,
  SIGN_USER_FAIL,

  LOAD_USER_REQUEST,
  LOAD_USER_SUCCESS,
  LOAD_USER_FAIL,

  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAIL,

  CLEAR_ERRORS,
  CLEAR_MESSAGES
} = userConstant;
